# Generated by Django 3.1.7 on 2021-04-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210402_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
