# Generated by Django 3.1.7 on 2021-04-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210402_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(default='XXXXX', max_length=255),
        ),
    ]
