# Generated by Django 3.1.7 on 2021-04-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sex',
        ),
        migrations.AddField(
            model_name='product',
            name='make',
            field=models.CharField(choices=[('M', 'Mitsubishi'), ('H', 'Honda'), ('T', 'Toyota')], default='', max_length=1),
        ),
    ]
