# Generated by Django 3.1.7 on 2021-04-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210402_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='make',
            field=models.CharField(choices=[('M', 'Mitsubishi'), ('H', 'Honda'), ('S', 'Subaru'), ('N', 'Nissan'), ('T', 'Unsure')], default='', max_length=1),
        ),
    ]
