# Generated by Django 3.1.7 on 2021-04-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210402_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='make',
            field=models.CharField(choices=[('Mitsubishi', 'Mitsubishi'), ('Honda', 'Honda'), ('Subaru', 'Subaru'), ('Nissan', 'Nissan'), ('Toyota', 'Toyota')], default='', max_length=100),
        ),
    ]
