# Generated by Django 3.1.7 on 2021-04-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210403_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default='XXXXX', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.IntegerField(),
        ),
    ]
