# Generated by Django 3.1.7 on 2021-04-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20210403_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='homepage/images/default.png', upload_to='homepage/images/'),
        ),
    ]
