# Generated by Django 3.1.7 on 2021-04-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20210403_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/products/default.png', upload_to='images/products/'),
        ),
    ]
