# Generated by Django 3.1.7 on 2021-03-31 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
